version: '3.4'

services:
    php:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./:/srv/app
            - ./admin-bundle:/srv/app/admin-bundle
        command: bash -c "symfony server:stop && symfony serve --dir=/srv/app/public"

    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: admin_test
            MYSQL_PASSWORD: admin_test
            MYSQL_DATABASE: admin_test
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    js:
        image: node:16
        volumes:
            - .:/srv/app
        working_dir: /srv/app
        command: bash -c "yarn encore dev --watch"
